CREATE TABLE LOGGING_EVENT (
    TIMESTAMP BIGINT NOT NULL,
    FORMATTED_MESSAGE NVARCHAR(MAX) NOT NULL,
    LOGGER_NAME NVARCHAR(254) NOT NULL,
    LEVEL_STRING NVARCHAR(254) NOT NULL,
    THREAD_NAME NVARCHAR(254),
    REFERENCE_FLAG SMALLINT,
    ARG0 NVARCHAR(254),
    ARG1 NVARCHAR(254),
    ARG2 NVARCHAR(254),
    ARG3 NVARCHAR(254),
    CALLER_FILENAME NVARCHAR(254),
    CALLER_CLASS NVARCHAR(254),
    CALLER_METHOD NVARCHAR(254),
    CALLER_LINE CHAR(4),
    EVENT_ID BIGINT IDENTITY PRIMARY KEY
);

CREATE TABLE LOGGING_EVENT_EXCEPTION (
    EVENT_ID BIGINT NOT NULL,
    I SMALLINT NOT NULL,
    TRACE_LINE NVARCHAR(MAX) NOT NULL
);

CREATE TABLE LOGGING_EVENT_PROPERTY (
    EVENT_ID BIGINT NOT NULL,
    MAPPED_KEY NVARCHAR(254) NOT NULL,
    MAPPED_VALUE NVARCHAR(MAX),
    PRIMARY KEY (EVENT_ID, MAPPED_KEY)
);

--verify
SELECT * FROM LOGGING_EVENT ORDER BY EVENT_ID DESC;
SELECT * FROM LOGGING_EVENT_EXCEPTION;
